### ISSUE TITLE
more than 1 word

### ISSUE THREAD

**Issue by sambfloyd** [jhlau/predom_sense#1]
Hi,

I'm trying to run this package for more than one word and I'm consistently getting this error for whatever the second-listed word is in the input. I'm actually using words/topics directly from the hdp-wsi model (add, ask). 

> Generating word distribution of dictionary senses...
> askcessing: Lemma = add ; pos = v
> Traceback (most recent call last):
>   File "GenWordnetSenses.py", line 74, in <module>
>     start_pattern = "the " + pos_map[pos] + " " + lemma + " have"
> KeyError: 'v\rask'
> Computing dictionary sense distribution and predominant sense...
> Traceback (most recent call last):
>   File "ComputeSenseRanking.py", line 129, in <module>
>     for sense, word_dist in sorted(dic_sense_dist[lemma].items()):
> KeyError: 'ask.v'

**Comment by sambfloyd** [comment]
this version of opennlp was not in /usr/bin so I believe this was what was causing the error initially. 

we specified the full file path of opennlp in the command which GenWordnetSenses tries to run at line 74, in addition to creating a link to predom_sense's opennlp  in /usr/local/bin
